# Generated by Django 5.0.1 on 2024-01-09 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcaptured',
            name='canopy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imgcaptured',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imgcaptured',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imgcaptured',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
