# Generated by Django 5.0.1 on 2024-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_alter_imgcaptured_canopy_alter_imgcaptured_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcaptured',
            name='image',
            field=models.ImageField(upload_to='imgcaptured/'),
        ),
    ]
